## Lecture 1

In [384]:

import pandas as pd
df=pd.read_csv('/Users/ironfeast/Desktop/python_project/pandas/data1/public.csv')
#df=pd.read_csv('/Users/ironfeast/Desktop/python_project/pandas/data1/public.csv',index_col='name of colum which you set index')
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [385]:
# This will give ou data on how many a csv contains right here like the number of rows and columns 
# this is not a method rather than a 
df.shape

(88883, 85)

In [386]:
# this is mehtod that give me more info about data like column name and there data types.
# object means string and int 64 just a integer
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [387]:
# If you want to see all the columns of your data then this one you should do
pd.set_option('display.max_columns', 85)# You can also do this for rows as well
# rerun your top cell.

In [388]:
# load another CSV file for further information
df_schema=pd.read_csv('/Users/ironfeast/Desktop/python_project/pandas/data1/schema.csv', index_col='Column')
df_schema

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [389]:
# head this one just gives you default 5 rows but you can pass value inside it to work like head(10) for 10 rows
df.head()
#similary df.tail() This one give you the last 5 rows

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

## Lecture 2 data frame and Series basic

In [390]:
# DataFrame is nothing but rows and column
# data frame converts data as a dictionary

frame=pd.DataFrame(df)

In [391]:
df['Hobbyist']# but this one is the best way to access data 
# df.Hobbyist is the same thing

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [392]:
frame['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [393]:
# you can also access multiple columns here with the help of a data frame
frame[['Hobbyist','OpenSource']]

      Hobbyist                                         OpenSource
0          Yes  The quality of OSS and closed source software ...
1           No  The quality of OSS and closed source software ...
2          Yes  The quality of OSS and closed source software ...
3           No  The quality of OSS and closed source software ...
4          Yes  OSS is, on average, of HIGHER quality than pro...
...        ...                                                ...
88878      Yes  The quality of OSS and closed source software ...
88879       No  The quality of OSS and closed source software ...
88880       No                                                NaN
88881       No  OSS is, on average, of HIGHER quality than pro...
88882      Yes  OSS is, on average, of HIGHER quality than pro...

[88883 rows x 2 columns]

In [394]:
#  loc and iloc  method
# iloc help us to find data by image and location per name suggest 
# This one returns data with the given index right down here
# like 
df.iloc[0]
# to access multiple rows with the help of above 
#df.iloc[[0,1]]
# if you also add the column which you want to acess in the rows you access
#df.iloc[[0,1],2] # the outer one is column number 
# df.loc[[0,1],['OpenSource','Hobbyist']]

Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object

In [395]:
df['Hobbyist']
df['Hobbyist'].value_counts()# this is different response from the data column

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [396]:
# rows access with slicing method
#df.loc[0:2, 'Hobbyist']
# If you also want to do slicing in a column like from where to where you want columns
df.loc[0:2, 'Hobbyist':'Employment']

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time

## Lecture 3 Indexing

In [397]:
# to make any column as index for the data frame
df.set_index('OpenSourcer')
# Here above you set Hobbyist as an index but it does not reflect quietly on the main data frame until you save using inplace =true
# Now with the help of this you can search anything using that index like before for searching you are doing
# df.loc[0] but now you can search like df.loc['put hobbyname']

,Respondent,MainBranch,Hobbyist,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
OpenSourcer,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Never,1,I am a student who is learning to code,Yes,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
Less than once per year,2,I am a student who is learning to code,No,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
Never,3,"I am not primarily a developer, but I write co...",Yes,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
Never,4,I am a developer by profession,No,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
Once a month or more often,5,I am a developer by profession,Yes,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Less than once a month but more than once per year,88377,NaN,Yes,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
Never,88601,NaN,No,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Never,88802,NaN,No,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Never,88816,NaN,No,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Less than once per year,88863,NaN,Yes,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [398]:
#df_schema.loc['row which you want,' column name which you want]
#df.sort_index(ascending=False) this will short your index descending order
df_schema.loc['Hobbyist', 'QuestionText']

'Do you code as a hobby?'

## Lecture 4 filtering

In [399]:
#dummy data

people={
    "key": [ "10", "11", "12","13"],
    "first": [ "durgesh", "kav", "anil","raju"],
    "last": ["tiwari","Rao","mas","tiwari"],
    "email": ["durgesh@gmail.com", "kvrao@gmail.com","animas@gmail.com","tiwar9@gamil.com"]
}

In [400]:
import pandas as pd
work=pd.DataFrame(people)

In [401]:
work

  key    first    last              email
0  10  durgesh  tiwari  durgesh@gmail.com
1  11      kav     Rao    kvrao@gmail.com
2  12     anil     mas   animas@gmail.com
3  13     raju  tiwari   tiwar9@gamil.com

In [402]:
work.set_index('key',inplace=True)

In [403]:
work

       first    last              email
key
10   durgesh  tiwari  durgesh@gmail.com
11       kav     Rao    kvrao@gmail.com
12      anil     mas   animas@gmail.com
13      raju  tiwari   tiwar9@gamil.com

In [404]:
# Filter out where the last name is tiwari
#work.index this methid help you get the index for the given dataframe 
# filter=(work['last']=='tiwari')
# work[filter]

In [405]:
# use the filter to filter out certain thing form out data set
filter=(df['ConvertedComp']>70000)
countries=['United States',' India',' Germany',' Canada']
fil=df['Country'].isin(countries)

In [406]:
df.loc[fil,['Country','WebFrameWorkedWith','DatabaseWorkedWith','ConvertedComp']]

,Country,WebFrameWorkedWith,DatabaseWorkedWith,ConvertedComp
3,United States,NaN,MySQL;SQLite,61000.0
12,United States,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Couchbase;DynamoDB;Firebase;MySQL,90000.0
21,United States,Angular/Angular.js;Ruby on Rails,Elasticsearch;MySQL;Oracle;Redis,103000.0
22,United States,React.js;Ruby on Rails,Oracle;SQLite,69000.0
25,United States,Angular/Angular.js;ASP.NET;Drupal;Express;jQue...,Microsoft SQL Server;MySQL;Redis;SQLite,114000.0
...,...,...,...,...
88818,United States,NaN,SQLite,NaN
88840,United States,NaN,NaN,NaN
88844,United States,Flask,NaN,NaN
88859,United States,NaN,NaN,NaN
88877,United States,React.js,NaN,NaN

In [407]:
lag_fil=df['LanguageWorkedWith'].str.contains('Python',na=False)

In [408]:
df.loc[lag_fil,['Country','LanguageWorkedWith','DatabaseWorkedWith','ConvertedComp']]

,Country,LanguageWorkedWith,DatabaseWorkedWith,ConvertedComp
0,United Kingdom,HTML/CSS;Java;JavaScript;Python,SQLite,NaN
1,Bosnia and Herzegovina,C++;HTML/CSS;Python,NaN,NaN
3,United States,C;C++;C#;Python;SQL,MySQL;SQLite,61000.0
4,Ukraine,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,NaN
7,India,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,NaN
...,...,...,...,...
88854,United Kingdom,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,PostgreSQL,NaN
88860,Brazil,Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):,NaN,NaN
88865,Switzerland,Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):,NaN,NaN
88872,Czech Republic,C;C++;HTML/CSS;JavaScript;PHP;Python;SQL,MySQL,NaN
88876,Spain,HTML/CSS;JavaScript;Python,MySQL;PostgreSQL,NaN

## Lecture 5 Updating Row and Columns

In [409]:
work

       first    last              email
key
10   durgesh  tiwari  durgesh@gmail.com
11       kav     Rao    kvrao@gmail.com
12      anil     mas   animas@gmail.com
13      raju  tiwari   tiwar9@gamil.com

In [410]:
# Chnage the colum name to uppper case
work.columns=[x.lower() for x in work.columns]
work

       first    last              email
key
10   durgesh  tiwari  durgesh@gmail.com
11       kav     Rao    kvrao@gmail.com
12      anil     mas   animas@gmail.com
13      raju  tiwari   tiwar9@gamil.com

In [411]:
# Rename Columns name for the given datadframe
work.rename(columns={'first':'first_name', 'last':'last_name'})

    first_name last_name              email
key
10     durgesh    tiwari  durgesh@gmail.com
11         kav       Rao    kvrao@gmail.com
12        anil       mas   animas@gmail.com
13        raju    tiwari   tiwar9@gamil.com

In [413]:
#Updating data in rows

#work.loc['10',['first_name','email']=['kamal','kamla@gmail.com']

In [414]:
work

       first    last              email
key
10   durgesh  tiwari  durgesh@gmail.com
11       kav     Rao    kvrao@gmail.com
12      anil     mas   animas@gmail.com
13      raju  tiwari   tiwar9@gamil.com

In [415]:
# to pass single you are not require to pass a list insted you can pass a name 
work.loc['tiwari',['email']]=['harsh@gmail.com']

In [416]:
work

          first    last              email
key
10      durgesh  tiwari  durgesh@gmail.com
11          kav     Rao    kvrao@gmail.com
12         anil     mas   animas@gmail.com
13         raju  tiwari   tiwar9@gamil.com
tiwari      NaN     NaN    harsh@gmail.com

In [417]:
# find the last name person and change his name
#filter=(work[last]=='tiwari')
#work[filter,'first']=['om']
#work.index

In [418]:
#methods
#apply-dataframe or series of object
#map
#applymap
#replace

#lenth of email address
work['email'].apply(len)

key
10        17
11        15
12        16
13        16
tiwari    15
Name: email, dtype: int64

In [419]:
def update_email(email):
    return email.upper()

In [420]:
work['email'].apply(update_email)

key
10        DURGESH@GMAIL.COM
11          KVRAO@GMAIL.COM
12         ANIMAS@GMAIL.COM
13         TIWAR9@GAMIL.COM
tiwari      HARSH@GMAIL.COM
Name: email, dtype: object

In [421]:
#using lambda fuction to reduce to lower case
work['email'].apply(lambda small:small.lower())

key
10        durgesh@gmail.com
11          kvrao@gmail.com
12         animas@gmail.com
13         tiwar9@gamil.com
tiwari      harsh@gmail.com
Name: email, dtype: object

In [422]:
# How many values in each row
work.apply(len,axis='columns')

key
10        3
11        3
12        3
13        3
tiwari    3
dtype: int64

In [423]:
#Number shows how many character per column are available and we can do some operation basis of that 
#work.applymap(len)

In [424]:
#replcae method
#work['first'].map({'kamal':'Kunal'}) using this one gives you nan value which you do not include in map
work['first'].replace({'kamal':'Kunal'})

key
10        durgesh
11            kav
12           anil
13           raju
tiwari        NaN
Name: first, dtype: object

## Lecture on stack data

In [425]:
df.rename(columns={'ConvertedComp':'SalaryUSD'},inplace=True)

In [426]:
df['SalaryUSD']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...
88878        NaN
88879        NaN
88880        NaN
88881        NaN
88882        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

In [427]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [428]:
# Here in place of replace you can also use map
df['Hobbyist'].replace({'Yes':'True','No':'False'}, inplace=True)

In [429]:
#df

## Lecture 6 add remove rows and columns

In [430]:
# to combine first and last name
work['first']+' '+work['last']

key
10        durgesh tiwari
11               kav Rao
12              anil mas
13           raju tiwari
tiwari               NaN
dtype: object

In [431]:
work['full_name']=work['first']+' '+work['last']

In [432]:
work

          first    last              email       full_name
key
10      durgesh  tiwari  durgesh@gmail.com  durgesh tiwari
11          kav     Rao    kvrao@gmail.com         kav Rao
12         anil     mas   animas@gmail.com        anil mas
13         raju  tiwari   tiwar9@gamil.com     raju tiwari
tiwari      NaN     NaN    harsh@gmail.com             NaN

In [433]:
work['full_name'].replace({'NaN':'Just Name'},inplace=True)

In [434]:
work

          first    last              email       full_name
key
10      durgesh  tiwari  durgesh@gmail.com  durgesh tiwari
11          kav     Rao    kvrao@gmail.com         kav Rao
12         anil     mas   animas@gmail.com        anil mas
13         raju  tiwari   tiwar9@gamil.com     raju tiwari
tiwari      NaN     NaN    harsh@gmail.com             NaN

In [435]:
# To drop any column in teh dataframe
#work.drop(columns=[pass list here],inplace=True)
#let's delete the first and last name form the data frame 
work.drop(columns=['first','last'], inplace=True)

In [439]:
work
work.drop(index=('tiwari'))

                 email       full_name
key
10   durgesh@gmail.com  durgesh tiwari
11     kvrao@gmail.com         kav Rao
12    animas@gmail.com        anil mas
13    tiwar9@gamil.com     raju tiwari

In [442]:
# as you see above we delete first and last name from the data frame and now try to get the ols one 
# this make a list from the full name and expand true means which make colum that we need to dd the final dataFrame

work['full_name'].str.split(' ', expand= True)

              0       1
key
10      durgesh  tiwari
11          kav     Rao
12         anil     mas
13         raju  tiwari
tiwari      NaN    None

In [443]:
work[['first','last']]=work['full_name'].str.split(' ', expand= True)

In [444]:
work

                    email       full_name    first    last
key
10      durgesh@gmail.com  durgesh tiwari  durgesh  tiwari
11        kvrao@gmail.com         kav Rao      kav     Rao
12       animas@gmail.com        anil mas     anil     mas
13       tiwar9@gamil.com     raju tiwari     raju  tiwari
tiwari    harsh@gmail.com             NaN      NaN    None

In [446]:
# add single row
x={
   
    "first": [ "ririr", "kav"],
    "last": ["tekekke","welcome"],
    "email": ["duelelelsh@gmail.com", "kekekkemo@gmail.com"]
}
df2=pd.DataFrame(x)

In [451]:
# append() method is dericated in pandas
newwork = pd.concat([work, df2], ignore_index=True)

In [453]:
newwork

                  email       full_name    first     last
0     durgesh@gmail.com  durgesh tiwari  durgesh   tiwari
1       kvrao@gmail.com         kav Rao      kav      Rao
2      animas@gmail.com        anil mas     anil      mas
3      tiwar9@gamil.com     raju tiwari     raju   tiwari
4       harsh@gmail.com             NaN      NaN     None
5  duelelelsh@gmail.com             NaN    ririr  tekekke
6   kekekkemo@gmail.com             NaN      kav  welcome

In [454]:
# Removing rows from the index method
newwork.drop(index=6)

                  email       full_name    first     last
0     durgesh@gmail.com  durgesh tiwari  durgesh   tiwari
1       kvrao@gmail.com         kav Rao      kav      Rao
2      animas@gmail.com        anil mas     anil      mas
3      tiwar9@gamil.com     raju tiwari     raju   tiwari
4       harsh@gmail.com             NaN      NaN     None
5  duelelelsh@gmail.com             NaN    ririr  tekekke

In [457]:
# To drop the rows where last name is Rao
index=(newwork['last']=='Rao')
newwork.drop(index=newwork[index].index)

                  email       full_name    first     last
0     durgesh@gmail.com  durgesh tiwari  durgesh   tiwari
2      animas@gmail.com        anil mas     anil      mas
3      tiwar9@gamil.com     raju tiwari     raju   tiwari
4       harsh@gmail.com             NaN      NaN     None
5  duelelelsh@gmail.com             NaN    ririr  tekekke
6   kekekkemo@gmail.com             NaN      kav  welcome

## Lecture 7 Sorting Data

In [458]:
# Sort data in pandas
newwork.sort_values(by='last',ascending=False)

                  email       full_name    first     last
6   kekekkemo@gmail.com             NaN      kav  welcome
0     durgesh@gmail.com  durgesh tiwari  durgesh   tiwari
3      tiwar9@gamil.com     raju tiwari     raju   tiwari
5  duelelelsh@gmail.com             NaN    ririr  tekekke
2      animas@gmail.com        anil mas     anil      mas
1       kvrao@gmail.com         kav Rao      kav      Rao
4       harsh@gmail.com             NaN      NaN     None

In [459]:
#you can also pass boolean value for ascending to sort data accordingly 
newwork.sort_values(by=['last','first'],ascending=False)

                  email       full_name    first     last
6   kekekkemo@gmail.com             NaN      kav  welcome
3      tiwar9@gamil.com     raju tiwari     raju   tiwari
0     durgesh@gmail.com  durgesh tiwari  durgesh   tiwari
5  duelelelsh@gmail.com             NaN    ririr  tekekke
2      animas@gmail.com        anil mas     anil      mas
1       kvrao@gmail.com         kav Rao      kav      Rao
4       harsh@gmail.com             NaN      NaN     None

In [463]:
df.sort_values(by=['Country','SalaryUSD'],inplace=True)

In [465]:
df['Country'].head(14)

28470    Afghanistan
719      Afghanistan
29560    Afghanistan
8112     Afghanistan
10697    Afghanistan
48122    Afghanistan
22327    Afghanistan
7056     Afghanistan
58082    Afghanistan
39018    Afghanistan
50172    Afghanistan
62723    Afghanistan
85185    Afghanistan
50437    Afghanistan
Name: Country, dtype: object

In [466]:
#Get 10 largest salary 
df['SalaryUSD'].nlargest(10)

25833    2000000.0
87353    2000000.0
21895    2000000.0
28080    2000000.0
72274    2000000.0
77665    2000000.0
79701    2000000.0
51798    2000000.0
75088    2000000.0
32056    2000000.0
Name: SalaryUSD, dtype: float64

In [467]:
#Rows where salary is highest
df.nlargest(10,'SalaryUSD')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
25833,25983,I am a developer by profession,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, full-stack",8,16,2,Very satisfied,Very satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,Solve a brain-teaser style puzzle;Interview wi...,No,Remote work options;Opportunities for professi...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,65500.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Office,Average,"Yes, because I see value in code review",2.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,Bash/Shell/PowerShell;C#;F#;Python;SQL;TypeScript,Microsoft SQL Server;MySQL,Microsoft SQL Server;MySQL,AWS;Docker;Heroku;Linux;MacOS;Raspberry Pi;Win...,AWS;Docker;Linux;MacOS;Windows,Angular/Angular.js,Angular/Angular.js;Flask;React.js,.NET;.NET Core;Node.js,.NET Core;Node.js,Notepad++;Sublime Text;Vim;Visual Studio;Visua...,Windows,Development;Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,Yes,Reddit,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87353,87896,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, full-stack",9,17,8,Very satisfied,Very satisfied,Somewhat confident,No,I am already a manager,I am not interested in new job opportunities,More than 4 years ago,Write any code;Interview with people in senior...,No,Office environment or company culture;Diversit...,"Something else changed (education, award, medi...",USD,United States dollar,55000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",3.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;Ruby;SQL;TypeScript,MariaDB;MySQL;PostgreSQL,MariaDB;MySQL;PostgreSQL,WordPress,NaN,jQuery;Laravel;Vue.js,Express;Laravel;Ruby on Rails;Vue.js,NaN,Node.js,Sublime Text;Vim;Visual Studio Code,Linux-based,I do not use containers,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,Twitter,Online,Handle,2011,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
21895,22013,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,2-9 employees,Academic researcher;Data scientist or machine ...,3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,1500000.0,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Clou...,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change ma...,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28080,28243,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, back-end;Developer, full-stack;Deve...",25,9,14,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles;Interview ...,Yes,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,USD,United States dollar,2000000.0,Yearly,2000000.0,20.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Not eno...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,NaN,C++;C#;Java;JavaScript;Objective-C;Python,C;C++;C#,PostgreSQL;SQLite,SQLite,Android;AWS;iOS;MacOS;Windows,Android;Linux,NaN,NaN,Node.js;Pandas;Unity 3D,Unity 3D;Unreal Engine,Android Studio;Coda;PyCharm;Visual Studio;Visu...,MacOS,I do not use containers,NaN,An irresponsible use of resources,No,Yes,No,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72274,72732,"I am not primarily a developer, but I write co...",False,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,NaN,NaN,4,20,5,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am actively looking for a job,More than 4 years ago,Write any code,No,Remote work options;Opportunities for professi...,I was preparing for a job search,USD,United States dollar,80000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,I have little or no influence,Java;Python;SQL,NaN,MongoDB;Microsoft SQL Server;MySQL;Oracle;Post...,MySQL,Android;Windows,AWS;Docker,NaN,Angular/Angular.js;React.js,NaN,NaN,Eclipse;Notepad++;PyCharm,Windows,Testing,NaN,NaN,Yes,Yes,No,WhatsApp,Neither,NaN,2017,A few times per month or weekly,Get a sense of belonging to the developer comm...,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Not sure,A lot less welcome now than last year,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
77665,78151,I am a developer by profession,True,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",15,18,10,Very satisfied,Very satisfied,Somewhat confident,No,Yes,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",Yes,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",USD,United States dollar,95000.0,Weekly,2000000.0,30.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,A little above average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;TypeScript;WebAssembly,Microsoft SQL Server,Microsoft SQL Server,Windows,Android;Arduino;Raspberry Pi,Angular/Angular.js;ASP.NET;jQuery;Vue.js,Angular/Angular.js;Vue.js,.NET,.NET Core;Xamarin,Visual Studio,Windows,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Yes,Yes,Reddit,In real life (in person),Username,2010,Multiple times per day,Learn how to do things I didn’t necessarily lo...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
79701,80200,I am a developer by profession,True,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,"1,000 to 4,999 employees","Developer, front-end;Developer, mobile",8,17,4,Very satisfied,Very satisfied,Somewhat confident,Yes,Yes,I am not interested in new job opportunities,More than 4 years ago,Complete a take-home project;Interview with pe...,No,Office environment or company culture;Diversit...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,120000.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Distracting work environment,A few days each month,Office,Average,"Yes, because I see value in code review",15.0,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Objective-C;Swift,Swift,NaN,NaN,Arduino;iOS;MacOS,Arduino;iOS;MacOS;Slack,NaN,NaN,NaN,NaN,Sublime Text;Vim;Xcode,MacOS,I do not use containers,Not at all,Useful for immutable record keeping outside of...,Yes,SIGH,Yes,Instagram,In real life (in person),Handle,2011,Multiple times per day,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,NaN,No,NaN,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Neutral,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
51798,52132,I am a developer by profession,True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Peru,No,Some college/university study without earning ...,I never declared a major,Completed an industry certification program (e...,100 to 499 employees,"Database administrator;Developer, back-end;Dev...",26,15,24,Slightly satisfied,Slightly dissatisfied,Not at all confident,No,I am already a manager,I am not interested in new job opportunities,3-4 years ago,Write any code;Interview with people in peer r...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,75000.0,Weekly,2000000.0,55.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings,All or almost all the time (I'm full-time remote),Home,Far above average,"Yes, because I see value in code review",6.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have a great deal of influence,C++;HTML/CSS;JavaScript;Python;SQL;TypeScript,C++;HTML/CSS;JavaScript;Rust;SQL;TypeScript;We...,Firebase;PostgreSQL,Firebase;PostgreSQL,Android;AWS;Docker;Linux;Microsoft Azure;Slack...,Android;Arduino;Kubernetes;Linux;Raspberry Pi,Express,Express,Ansible;Cordova;Node.js,Ansible;Cordova;Node.js,Vim;Visual Studio Code,Linux-based,Development;Testing;Production,Not at all,A passing fad,No,SIGH,What?,WhatsApp,Neither,Username,2008,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,48.0,Man,NaN,NaN,Black or of African descent;East Asian;Hispani...,Yes,Appropriate in length,Easy
75088,75561,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Singapore,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A humanities discipline (ex. literature, histo...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Developer, front-end;Devel...",19,10,16,Very satisfied,Very satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,1-2 years ago,Complete a take-home project;Interview with pe...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,223000.0,Monthly,2000000.0,38.0,There's no schedule or spec; I work on what se...,"Meetings;Non-work commitments (parenting, scho...","More than half, but not all, the time",Home,Far above average,No,NaN,"Yes, it's part of our process",Not sure,I have little or no influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...,Bash/Shell/PowerShell;F#;HTML/CSS;JavaScript;P...,DynamoDB;Elasticsearch;PostgreSQL,DynamoDB;Elasticsearch;PostgreSQL,AWS;Linux;MacOS,AWS;Linux;MacOS,React.js,React.js,Node.js,Node.js;React Native,Vim;Visual Studio Code,MacOS,Development,Non-currency applications of blockchain,NaN,No,Yes,Yes,Twitter,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,The other resource was much faster,11-30 minutes,Yes,A few times per week,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
32056,32250,I am a developer by profession,True,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,Switzerland,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,2-9 employees,Academic researcher;Data scientist or machine ...,16,14,9,Slightly satisfied,Very satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",USD,United States dollar,200000.0,Monthly,2000000.0,50.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Non-wor...,All or almost all the time (I'm full-time remote),Home,Far above average,"Yes, because I see value in code review",20.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,C#;Go;HTML/CSS;JavaScript;Python;SQL;TypeScript,C#;HTML/CSS;JavaScript,DynamoDB;Elasticsearch;Redis,DynamoDB;Elasticsearch,Android;AWS;Docker;Google Cloud Platform;IBM C...,AWS;Linux,ASP.NET;Express;React.js;Vue.js,Vue.js,.NET Core;Node.js;TensorFlow,Node.js,Visual Studio Code,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,Also Yes,Yes,Twitter,Online,NaN,2008,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're intere...,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy

## Lecture 8 Aggregate and Analyzing

In [469]:
df['SalaryUSD'].head(15)

28470          0.0
719            0.0
29560       1116.0
8112        1596.0
10697       3996.0
48122       4464.0
22327       7980.0
7056       14364.0
58082      17556.0
39018      19152.0
50172     153216.0
62723    1000000.0
85185          NaN
50437          NaN
88340          NaN
Name: SalaryUSD, dtype: float64

In [471]:
df['SalaryUSD'].median()

57287.0

In [475]:
# This gives a broad idea about your data set
df.describe()

,Respondent,CompTotal,SalaryUSD,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [476]:
df['SalaryUSD'].count()

55823

In [477]:
# to know how many people code in there free time 
df['Hobbyist'].value_counts()

Hobbyist
True     71257
False    17626
Name: count, dtype: int64

In [491]:
#df['SocialMedia'].value_counts()
val=df['SocialMedia'].value_counts(normalize=True)# this will give you the percentege of user of what
val

SocialMedia
Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: proportion, dtype: float64

In [483]:
df_schema.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [497]:
# use of group by function
group_by=df.groupby(['Country'])

In [493]:
group_by

In [498]:
group_by.get_group('United States')

In [500]:
# you can also get the same thing using filter method
fil=(df['Country']=='United States')
df.loc[fil]['SocialMedia'].value_counts()

SocialMedia
Reddit                      5700
Twitter                     3468
Facebook                    2844
YouTube                     2463
I don't use social media    1851
Instagram                   1652
LinkedIn                    1020
WhatsApp                     609
Snapchat                     326
WeChat 微信                     93
VK ВКонта́кте                  9
Weibo 新浪微博                     8
Hello                          2
Youku Tudou 优酷                 1
Name: count, dtype: int64

In [502]:
group_by['SocialMedia'].value_counts().head(30)

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
             LinkedIn                     1
             Twitter                      1
Albania      WhatsApp                    18
             Facebook                    16
             Instagram                   13
             YouTube                     10
             Twitter                      8
             LinkedIn                     7
             Reddit                       6
             I don't use social media     4
             Snapchat                     1
             WeChat 微信                    1
Algeria      YouTube                     42
             Facebook                    41
             Twitter                     14
             LinkedIn                     9
             Instagram                    7
             I don't use social media     7
             Reddit                       2
             WhatsApp                     2
Andorra      Facebook                     2
             I don't use social media     2
             YouTube                      1
             Reddit                       1
             Snapchat                     1
Name: count, dtype: int64

In [504]:
group_by['SalaryUSD'].median()

Country
Afghanistan                               6222.0
Albania                                  10818.0
Algeria                                   7878.0
Andorra                                 160931.0
Angola                                    7764.0
                                          ...
Venezuela, Bolivarian Republic of...      6384.0
Viet Nam                                 11892.0
Yemen                                    11940.0
Zambia                                    5040.0
Zimbabwe                                 19200.0
Name: SalaryUSD, Length: 179, dtype: float64

In [506]:
# mean and median salary country wise
group_by['SalaryUSD'].agg(['median','mean'])
group_by['SalaryUSD'].agg(['median','mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [511]:
# How to get the country people know python 
df_python=group_by['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())
df_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [512]:
response_python=df['Country'].value_counts()
response_python

Country
United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
North Korea                             1
Niger                                   1
Saint Vincent and the Grenadines        1
Chad                                    1
Brunei Darussalam                       1
Name: count, Length: 179, dtype: int64

In [513]:
python_all=pd.concat([df_python,response_python], axis='columns', sort=False)

In [514]:
python_all

                                      LanguageWorkedWith  count
Country
Afghanistan                                            8     44
Albania                                               23     86
Algeria                                               40    134
Andorra                                                0      7
Angola                                                 2      5
...                                                  ...    ...
Venezuela, Bolivarian Republic of...                  28     88
Viet Nam                                              78    231
Yemen                                                  3     19
Zambia                                                 4     12
Zimbabwe                                              14     39

[179 rows x 2 columns]

In [517]:
python_all.rename(columns={'LanguageWorkedWith':'KnowsPython','count':'TotalPeople'},inplace=True)

In [518]:
python_all

                                      KnowsPython  TotalPeople
Country
Afghanistan                                     8           44
Albania                                        23           86
Algeria                                        40          134
Andorra                                         0            7
Angola                                          2            5
...                                           ...          ...
Venezuela, Bolivarian Republic of...           28           88
Viet Nam                                       78          231
Yemen                                           3           19
Zambia                                          4           12
Zimbabwe                                       14           39

[179 rows x 2 columns]

In [528]:
python_all['PythonsKnowsPercent']=((python_all['KnowsPython']/python_all['TotalPeople'])*100)

In [529]:
python_all

,KnowsPython,TotalPeople,PythonsKnows,PythonsKnowsPercent
Country,,,,
Dominica,1,1,100.000000,100.000000
Niger,1,1,100.000000,100.000000
Timor-Leste,1,1,100.000000,100.000000
Sao Tome and Principe,1,1,100.000000,100.000000
Turkmenistan,6,7,85.714286,85.714286
...,...,...,...,...
Tonga,0,1,0.000000,0.000000
North Korea,0,1,0.000000,0.000000
Papua New Guinea,0,1,0.000000,0.000000
Tajikistan,0,7,0.000000,0.000000
Lao People's Democratic Republic,0,3,0.000000,0.000000

In [530]:
python_all.sort_values(by='PythonsKnowsPercent',ascending=False,inplace=True)

In [531]:
python_all

,KnowsPython,TotalPeople,PythonsKnows,PythonsKnowsPercent
Country,,,,
Dominica,1,1,100.000000,100.000000
Sao Tome and Principe,1,1,100.000000,100.000000
Niger,1,1,100.000000,100.000000
Timor-Leste,1,1,100.000000,100.000000
Turkmenistan,6,7,85.714286,85.714286
...,...,...,...,...
Brunei Darussalam,0,1,0.000000,0.000000
Antigua and Barbuda,0,9,0.000000,0.000000
Andorra,0,7,0.000000,0.000000
Djibouti,0,2,0.000000,0.000000
Lao People's Democratic Republic,0,3,0.000000,0.000000

In [532]:

python_all.loc['United States']

KnowsPython            10083.000000
TotalPeople            20949.000000
PythonsKnows              48.131176
PythonsKnowsPercent       48.131176
Name: United States, dtype: float64

In [537]:
# drop PythonsKnows 
python_all.drop('PythonsKnows', axis=1, inplace=True)

In [538]:
python_all

,KnowsPython,TotalPeople,PythonsKnowsPercent
Country,,,
Dominica,1,1,100.000000
Sao Tome and Principe,1,1,100.000000
Niger,1,1,100.000000
Timor-Leste,1,1,100.000000
Turkmenistan,6,7,85.714286
...,...,...,...
Brunei Darussalam,0,1,0.000000
Antigua and Barbuda,0,9,0.000000
Andorra,0,7,0.000000
Djibouti,0,2,0.000000
Lao People's Democratic Republic,0,3,0.000000

## Lecture 9 Cleaning and clustering

In [539]:
import pandas as pd
import numpy as np
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [543]:
handle = pd.DataFrame(people)

In [544]:
handle

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [545]:
# drop NAN in given data frame
handle.dropna()

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [547]:
# now put default argument to delete data
# how-> can be aby or all any for delete if some of them are null and all if all of them null
handle.dropna(axis='index', how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [552]:
# This one deletes rows where email is not there and other elements represent if this much is present in the table then the rows is not going to delete 
# all mean that there is drop of the row if there is no attribute present which is mentioned in subset 
handle.dropna(axis='index', how='all',subset=['email', 'last'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [555]:
# replace other NA and missing with np.nan to better handle it 
handle.replace('NA',np.nan, inplace=True)
handle.replace('Missing',np.nan, inplace=True)

In [556]:
handle

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
4    NaN      NaN                      NaN  None
5   None      NaN      Anonymous@email.com  None
6    NaN      NaN                      NaN   NaN

In [557]:
handle.dropna()

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [563]:
# to know about attribute type
handle.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [562]:
handle['age']=handle['age'].astype(float)

In [564]:
handle['age'].mean()

46.75

## Stack Data

In [570]:
df['YearsCode'].unique()

array(['36', 'Less than 1 year', '10', '2', '4', '3', '7', '6', '8', nan,
       '1', '20', '28', '31', '9', '5', 'More than 50 years', '12', '18',
       '17', '15', '13', '35', '14', '21', '11', '23', '22', '19', '25',
       '40', '39', '33', '16', '24', '32', '30', '38', '29', '34', '26',
       '27', '43', '48', '46', '37', '42', '47', '44', '45', '41', '49',
       '50'], dtype=object)

In [576]:
# Replace these string come in between we can do following
df['YearsCode'].replace('More than 50 years',0,inplace=True)
df['YearsCode'].replace('Less than 1 year',0,inplace=True)

In [577]:
df['YearsCode'].unique()

array(['36', 0, '10', '2', '4', '3', '7', '6', '8', nan, '1', '20', '28',
       '31', '9', '5', '12', '18', '17', '15', '13', '35', '14', '21',
       '11', '23', '22', '19', '25', '40', '39', '33', '16', '24', '32',
       '30', '38', '29', '34', '26', '27', '43', '48', '46', '37', '42',
       '47', '44', '45', '41', '49', '50'], dtype=object)

In [580]:
df['YearsCode']=df['YearsCode'].astype(float)

In [581]:
df['YearsCode'].unique()

array([36.,  0., 10.,  2.,  4.,  3.,  7.,  6.,  8., nan,  1., 20., 28.,
       31.,  9.,  5., 12., 18., 17., 15., 13., 35., 14., 21., 11., 23.,
       22., 19., 25., 40., 39., 33., 16., 24., 32., 30., 38., 29., 34.,
       26., 27., 43., 48., 46., 37., 42., 47., 44., 45., 41., 49., 50.])

df['YearsCode'].mean()

## Lecture 10 Time series Date

In [648]:

from datetime import datetime
#val = pd.read_csv('/Users/ironfeast/Desktop/python_project/pandas/ETH_1h.csv')

#val['Date']= pd.to_datetime(val['Date'],format='%Y-%m-%d %I-%p')

d_parser = lambda x:datetime.strptime(x, '%Y-%m-%d %I-%p')
val= pd.read_csv('/Users/ironfeast/Desktop/python_project/pandas/ETH_1h.csv', parse_dates=['Date'], date_parser=d_parser)

/var/folders/lq/hmf_y1195c900x0nt4s1_b1h0000gn/T/ipykernel_6003/406560374.py:7: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  val= pd.read_csv('/Users/ironfeast/Desktop/python_project/pandas/ETH_1h.csv', parse_dates=['Date'], date_parser=d_parser)

In [649]:
val. shape

(23674, 7)

In [650]:
val.head()

                 Date  Symbol    Open    High     Low   Close      Volume
0 2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1 2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2 2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3 2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4 2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [651]:
val['Date']

0       2020-03-13 20:00:00
1       2020-03-13 19:00:00
2       2020-03-13 18:00:00
3       2020-03-13 17:00:00
4       2020-03-13 16:00:00
                ...
23669   2017-07-01 15:00:00
23670   2017-07-01 14:00:00
23671   2017-07-01 13:00:00
23672   2017-07-01 12:00:00
23673   2017-07-01 11:00:00
Name: Date, Length: 23674, dtype: datetime64[ns]

In [652]:
val['Date'].dt.day_name()

0          Friday
1          Friday
2          Friday
3          Friday
4          Friday
           ...
23669    Saturday
23670    Saturday
23671    Saturday
23672    Saturday
23673    Saturday
Name: Date, Length: 23674, dtype: object

In [653]:
val['DayOfWeek']=val['Date'].dt.day_name()

In [654]:
val

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [655]:
# earliest and later date in data 
val['Date'].min()

Timestamp('2017-07-01 11:00:00')

In [656]:
val['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [657]:
# time betwen two dates
val['Date'].max()-val['Date'].min()

Timedelta('986 days 09:00:00')

In [661]:
val.set_index('Date')

,Symbol,Open,High,Low,Close,Volume,DayOfWeek
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...
2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [662]:
#fil_date=(val['Date']> '=2020')
val.loc(fil_date)

NameError: name 'fil_date' is not defined

In [664]:
# this is using range query here 

#val['2020-01':'2020-02']

## Lecture 11 Reading and Writing data

In [670]:
fil=(df['Country']=='India')
india_df=df[fil].head(15)

In [673]:
# Write into new csv file
india_df.to_csv('/Users/ironfeast/Desktop/python_project/pandas/data1/india.csv')

In [675]:
# Write into another formate
india_df.to_csv('/Users/ironfeast/Desktop/python_project/pandas/data1/luck.csv',sep='\t')

In [676]:
! pip3 install xlwt openpyxl xlrd

Collecting xlwt
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 4.8 MB/s eta 0:00:00
Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 2.6 MB/s eta 0:00:00a 0:00:01
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.5/96.5 kB 6.4 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: xlwt, xlrd, et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2 xlrd-2.0.1 xlwt-1.3.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip3 install --upgrade pip

In [677]:
# Write to xl file 
india_df.to_excel('/Users/ironfeast/Desktop/python_project/pandas/data1/luck.xlsx')

In [678]:
# Write on JSON file 
india_df.to_json('/Users/ironfeast/Desktop/python_project/pandas/data1/luck.json')

In [687]:
#from sqlalchemy import create_engine
#import psycopg2

In [688]:
# this help you to write in postgres sql
#! pip3 install sqlalchemy psycopg2